import ibm_boto3
from ibm_botocore.client import Config, ClientError

COS_ENDPOINT="https://s3.jp-tok.cloud-object-storage.appdomain.cloud"
COS_API_KEY_ID="4PRO39HenyMGBDy0pI0YNlGv_eB4EfFdeZhnHdUaiZyl"
COS_INSTANCE_CRN="crn:v1:bluemix:public:cloud-object-storage:global:a/d6ac2c7047984c429afc53c2cc9d9f94:cdfd745b-c197-45b3-8bb1-ef5a1f8cefaf::"
COS_BUCKET_LOCATION="jp-tok-smart"

cos = ibm_boto3.resource("s3",
    ibm_api_key_id=COS_API_KEY_ID,
    ibm_service_instance_id=COS_INSTANCE_CRN,
    config=Config(signature_version="oauth"),
    endpoint_url=COS_ENDPOINT
)
